export const RECEIVE_USERS = 'RECEIVE_USERS'
export const LOAD_USER = 'LOAD_USER'
export const LOAD_SHOWS = 'LOAD_SHOWS'
export const LOAD_USER_SHOWS = 'LOAD_USER_SHOWS'
export const ADD_COMMENTS = 'ADD_COMMENTS'
export const LOAD_COMMENTS = 'LOAD_COMMENTS'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_OUT = 'LOGIN_OUT'